name: TS_AppsMovil
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.18.0+1
  google_sign_in: ^4.5.4
  flutter_gherkin: 1.1.8+9
  flutter_bloc: ^4.0.0
  equatable: ^1.2.5
  meta: 1.3.0-nullsafety.3
  rxdart: ^0.24.1
  splashscreen: ^1.2.0
  flutter_auth_buttons: ^0.10.0  
  firebase_core: ^0.5.0
  firebase_analytics: ^6.0.0
  firebase_database: ^4.0.0
  firebase_storage: ^4.0.0
  cloud_firestore: ^0.14.0+2
  cupertino_icons: ^0.1.3
  flutter_facebook_login: ^3.0.0
  shared_preferences: ^0.5.12
  flutter_login_facebook: ^0.2.1
  flutter_signin_button: ^1.1.0
  flutter_facebook_auth: "^0.2.3"
  image_picker: ^0.6.7+11
  intl: ^0.16.1
  font_awesome_flutter: ^8.8.1
  


dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any
  flutter_test:
    sdk: flutter
  mockito: ^4.0.0
  bloc_test: ^5.0.0

#  firebase_auth_mocks: ^0.3.1
#  google_sign_in_mocks: ^0.1.0+2
#  bloc_test: 5.0.0


# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/loading_blue_circle.gif
